import { ApiErrorMessagesEnum as ErrorCode } from "./apiMessages";

export enum ApiErrorCodesEnum {
  OPERATION_NOT_ALLOWED = ErrorCode.OPERATION_NOT_ALLOWED,
  TOO_MANY_ATTEMPTS_TRY_LATER = ErrorCode.TOO_MANY_ATTEMPTS_TRY_LATER,

  TOKEN_EXPIRED = ErrorCode.TOKEN_EXPIRED,
  CREDENTIAL_TOO_OLD_LOGIN_AGAIN = ErrorCode.CREDENTIAL_TOO_OLD_LOGIN_AGAIN,
  INVALID_REFRESH_TOKEN = ErrorCode.INVALID_REFRESH_TOKEN,

  USER_DISABLED = ErrorCode.USER_DISABLED,
  USER_NOT_FOUND = ErrorCode.USER_NOT_FOUND,

  MISSING_EMAIL = ErrorCode.MISSING_EMAIL,
  INVALID_EMAIL = ErrorCode.INVALID_EMAIL,
  EMAIL_NOT_FOUND = ErrorCode.EMAIL_NOT_FOUND,
  EMAIL_EXISTS = ErrorCode.EMAIL_EXISTS,

  INVALID_PASSWORD = ErrorCode.INVALID_PASSWORD,
  WEAK_PASSWORD = ErrorCode.WEAK_PASSWORD,
  EXPIRED_OOB_CODE = ErrorCode.EXPIRED_OOB_CODE,
}
