export enum StorageItems {
  FIREBASE_TOKEN = "FIREBASE_TOKEN",
  FIREBASE_REFRESH_TOKEN = "FIREBASE_REFRESH_TOKEN",
  FIREBASE_TOKEN_EXPIRATION_DATE = "FIREBASE_TOKEN_EXPIRATION_DATE",
  FIREBASE_USER_ID = "FIREBASE_USER_ID",
}
